//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoteClip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Round
    {
        public Round()
        {
            this.Videos = new HashSet<Video>();
        }
    
        public int idRound { get; set; }
        public string nameRound { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string ruleRound { get; set; }
    
        public virtual ICollection<Video> Videos { get; set; }
    }
}
