//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoteClip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.VotingVideos = new HashSet<VotingVideo>();
        }
    
        public int idUser { get; set; }
        public string emailUser { get; set; }
    
        public virtual ICollection<VotingVideo> VotingVideos { get; set; }
    }
}
