//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoteClip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public Video()
        {
            this.VotingVideos = new HashSet<VotingVideo>();
        }
    
        public int idVideo { get; set; }
        public string titleVideo { get; set; }
        public string authorVideo { get; set; }
        public string describeVideo { get; set; }
        public string urlVideo { get; set; }
        public Nullable<int> idRound { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    
        public virtual Round Round { get; set; }
        public virtual ICollection<VotingVideo> VotingVideos { get; set; }
    }
}
